### ISSUE TITLE
Are you sure auto-updating is correctly set up?

### ISSUE THREAD

**Issue by vitorgalvao** [1000ch/whale#12]
I’ve tested this on the last two versions of Whale. Auto-updating does not seem to work. Are you sure it’s set up correctly?

Specifically, is the app signed? Because [Whale needs to be signed for auto-updating to work](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#macos).

**Comment by 1000ch** [comment]
Whale.app seems to be signed correctly, but [update feed does not work well](https://github.com/1000ch/whale/blob/master/update.js#L47). It's a problem of json server, not of this app 😢

**Comment by vitorgalvao** [comment]
What about hosting the JSON in this repo? Would that not work?

**Comment by 1000ch** [comment]
@vitorgalvao Nice idea, I'll try.

**Comment by 1000ch** [comment]
Finally fixed from `v0.10.3`.
