### ISSUE TITLE
Allow zoom

### ISSUE THREAD

**Issue by tkafka** [1000ch/whale#13]
Hi, I'd be grateful for allowing zoom control (cmd+plus, cmd+minus, cmd+0 to reset) - trello is rather big and well readable at eg. 80 %, it would help me fit the lists I need onscreen when on my laptop.

Thanks for considering! Tomas

**Comment by tkafka** [comment]
Created pull request - implementing it was easier than I thought :).
https://github.com/1000ch/whale/pull/14

**Comment by 1000ch** [comment]
https://github.com/1000ch/whale/pull/14#issuecomment-645298388
