### ISSUE TITLE
Whale is shown as Electron in Task Manager on Windows

### ISSUE THREAD

**Issue by jreznot** [1000ch/whale#15]
It seems that Whale for windows is built with incorrect electron-packager options

![whale-electron](https://user-images.githubusercontent.com/1066152/29493251-cc237f88-85a3-11e7-997a-790648984c2f.png)

**Comment by 1000ch** [comment]
I believe this is solved on the newest version which [uses the `productName` of `package.json`](https://github.com/electron-userland/electron-builder/releases/tag/v10.4.3) now.
