### ISSUE TITLE
Trello just released an official app

### ISSUE THREAD

**Issue by vitorgalvao** [1000ch/whale#18]
Available on the Mac App Store: https://itunes.apple.com/app/trello/id1278508951.

It’s also an electron wrapper but has other nice additions, such as multiple windows. Not sure if you want to keep developing whale or not.

**Comment by Trumpy** [comment]
There is no linux support so that is a target :/

**Comment by abatkin** [comment]
Not only is it missing Linux support as Trumpy mentioned, but on Windows, it is only available via the Windows Store, which means many devices (like Windows 7) are left out.

**Comment by vitorgalvao** [comment]
All good reasons.
