### ISSUE TITLE
app icon is missing on ubuntu 19.10 gnome 3.34.1

### ISSUE THREAD

**Issue by souhaiebtar** [1000ch/whale#23]
Peace,

first thanks for all your hard work, the icon is missing,
i think it would be better to hard code the icon location in .desktop file, thanks again,
i copied an svg from the web under /opt/whale than i changed the path in the `.desktop` file, now it shows correctly.

`whale.desktop` file
```
[Desktop Entry]
Name=Whale
Comment=Whale is unofficial app for Trello.
Exec="/opt/Whale/whale" %U
Terminal=false
Type=Application
Icon=/opt/Whale/trello.svg
StartupWMClass=Whale
Categories=Productivity;
```

greetings

**Comment by 1000ch** [comment]
Would you still face this problem after you update Whale to the newest? and if so, I want to know the kind of your Linux distributes.

**Comment by ViniciusBRodrigues** [comment]
Hi, I'm having this issue in Linux Mint Debbie. The icon in the system is missing, while the icon tray is ok.
