### ISSUE TITLE
トラブル「お使いのブラウザでTrelloのリソースを読み込めませんでした」

### ISSUE THREAD

**Issue by kntmrkm** [1000ch/whale#3]
<img width="844" alt="whale_ __users_kntmrkm_dropbox_ _ _ __applications" src="https://cloud.githubusercontent.com/assets/2703486/22051052/622d5216-dd83-11e6-8aa6-b8bfd1a05750.png">

添付画像のように表示され、ログイン処理もできない状態になりました。

本日から表示が全くされなかったのでアプリを削除して再インストールし直しました。

**Comment by 1000ch** [comment]
再インストールしたあとは回復しましたか？
アプリケーション側ではネットワークに関する処理はしていない（つもり）なので、
再発・頻発するようであれば再現手順、あるいはネットワーク環境等を報告いただけますと幸いです。

**Comment by kntmrkm** [comment]
再インストール後も症状変わらずでした。

`sudo killall -HUP mDNSResponder`でＤNSキャッシュもクリアしてみたのですが。
ネットワーク環境は物理的に２箇所で利用していますが、どちらでも症状は一緒でした。

再起動などしてみて様子を見てみます。

**Comment by vitorgalvao** [comment]
Why did you close this, @kntmrkm? It seems to still be unresolved, even for you.

I too have this problem.

**Comment by kntmrkm** [comment]
@vitorgalvao 
OK. I'm using alternative way. http://fluidapp.com
I thought because of my env.

reopen this.

**Comment by vitorgalvao** [comment]
Just built this from master. That version works.

**Comment by weblogix** [comment]
@kntmrkm Did you get this resolved?  I built the app myself and it works now.

Here's a link to my build - https://dl.dropboxusercontent.com/u/1992270/Whale-macos-v0.6.0.zip

**Comment by kntmrkm** [comment]
@weblogix The build works!

Thanks.
