### ISSUE TITLE
Can't change login email

### ISSUE THREAD

**Issue by bryanzzhu** [1000ch/whale#44]
I typo'd my email while trying to login on my first attempt. It naturally failed and I ended up on the "Sign up for your account" page. However, every time I try to click the "Already have an Atlassian account? Log in" option, it seems to auto-submit the old incorrect email and redirects me back to the "Sign up for your account" page less than half a second later. So the end result is that I'm now stuck on the "Sign up for your account" page.

**Comment by 1000ch** [comment]
Would you try to type `⌘` + `Shift` + `H` to move back to Home?

**Comment by bryanzzhu** [comment]
That did the trick, thanks! `Ctrl` + `Shift` + `H` on Windows.
