### ISSUE TITLE
Start with Windows

### ISSUE THREAD

**Issue by karanrajpal14** [1000ch/whale#7]
An option to start Whale with Windows would be nice. Can you please add that?

**Comment by 1000ch** [comment]
Do you mean [Whale for Windows](https://github.com/1000ch/whale/releases/tag/v0.7.1)?

**Comment by karanrajpal14** [comment]
Yes, precisely. I'd like for it to start up along with Windows since I use it all the time.

**Comment by 1000ch** [comment]
You can configure Whale as start-up program on Windows.
