### ISSUE TITLE
Cannot Download attached files

### ISSUE THREAD

**Issue by bboure** [1000ch/whale#8]
Hi,

Thanks for your great work on this promising app.

I found an issue when trying to download an attached file.
When I click on the "Download" link of the file, nothing happens.

![image](https://cloud.githubusercontent.com/assets/7089997/23123342/45d40944-f768-11e6-8ee2-936d36a65c73.png)

**Comment by 1000ch** [comment]
@bboure 
Ah, there is no feedback from Whale as you say.
But I could download a file from Whale and found it on `~/Downloads`.
