### ISSUE TITLE
Log In button is not selectable

### ISSUE THREAD

**Issue by binhonglee** [1000ch/whale#9]
![screen shot 2017-03-27 at 3 05 49 pm](https://cloud.githubusercontent.com/assets/16726210/24380219/232ee546-12ff-11e7-9dcf-a93488e1eca1.png)

As seen in the screenshot, even after typing in the credentials, the "Log In" button is still not selectable. I tried going to Trello on my browser to make sure this is not a connection firewall issue and it worked fine.

**Comment by 1000ch** [comment]
Which version of app?

**Comment by binhonglee** [comment]
Sorry for the lack of info, I install this with brew on a Mac. Seems like brew might be maintaining an older version. I installed it through the release download of 0.7.2 and it now works just fine.
